#!/usr/bin/env python3
"""
Comprehensive translation fix for Jupyter notebooks.
Reads Portuguese originals and creates proper English translations.
"""
import json
import os
import re

def clean_translate_markdown(text):
    """Translate markdown text from Portuguese to English."""
    
    # Common Portuguese words and phrases - comprehensive list
    replacements = [
        # Pronouns and basic words
        (r'\bvocê\b', 'you'),
        (r'\bvocês\b', 'you'),
        (r'\bvoces\b', 'you'),
        (r'\bvocé\b', 'you'),
        
        # Verbs - future tense
        (r'\bserá\b', 'will be'),
        (r'\bserão\b', 'will be'),
        (r'\bgerará\b', 'will generate'),
        (r'\bvisualizará\b', 'will visualize'),
        (r'\bcriará\b', 'will create'),
        (r'\bmostrará\b', 'will show'),
        (r'\bexibirá\b', 'will display'),
        (r'\busará\b', 'will use'),
        (r'\bprocessará\b', 'will process'),
        (r'\bcalculará\b', 'will calculate'),
        
        # Verbs - subjunctive/possibility
        (r'\bpossa\b', 'can'),
        (r'\bpossam\b', 'can'),
        (r'\bpossamos\b', 'we can'),
        
        # Verbs - present/infinitive
        (r'\bpode\b', 'can'),
        (r'\bpodem\b', 'can'),
        (r'\bpodemos\b', 'we can'),
        (r'\bdeve\b', 'must'),
        (r'\bdevem\b', 'must'),
        (r'\bdevemos\b', 'we must'),
        (r'\bprecisa\b', 'needs'),
        (r'\bprecisam\b', 'need'),
        (r'\bprecisamos\b', 'we need'),
        (r'\btem\b', 'has'),
        (r'\btêm\b', 'have'),
        (r'\btemos\b', 'we have'),
        (r'\bteremos\b', 'we will have'),
        (r'\bfaz\b', 'does'),
        (r'\bfazem\b', 'do'),
        (r'\bfazemos\b', 'we do'),
        (r'\bfazer\b', 'to do'),
        (r'\bvai\b', 'will'),
        (r'\bvão\b', 'will'),
        (r'\bvamos\b', "let's"),
        (r'\birá\b', 'will'),
        (r'\birão\b', 'will'),
        (r'\biremos\b', 'we will'),
        
        # Verbs - present tense actions
        (r'\bexibe\b', 'displays'),
        (r'\bexibem\b', 'display'),
        (r'\bexibir\b', 'to display'),
        (r'\bexibiremos\b', 'we will display'),
        (r'\bgera\b', 'generates'),
        (r'\bgeram\b', 'generate'),
        (r'\bgerar\b', 'to generate'),
        (r'\bgeraremos\b', 'we will generate'),
        (r'\bmostra\b', 'shows'),
        (r'\bmostram\b', 'show'),
        (r'\bmostrar\b', 'to show'),
        (r'\bmostraremos\b', 'we will show'),
        (r'\busa\b', 'uses'),
        (r'\busam\b', 'use'),
        (r'\busar\b', 'to use'),
        (r'\busaremos\b', 'we will use'),
        (r'\busamos\b', 'we use'),
        (r'\bcria\b', 'creates'),
        (r'\bcriam\b', 'create'),
        (r'\bcriar\b', 'to create'),
        (r'\bcriaremos\b', 'we will create'),
        (r'\bcriamos\b', 'we create'),
        (r'\bvisualiza\b', 'visualizes'),
        (r'\bvisualizam\b', 'visualize'),
        (r'\bvisualizar\b', 'to visualize'),
        (r'\bvisualizaremos\b', 'we will visualize'),
        (r'\bvisualizamos\b', 'we visualize'),
        (r'\bcarrega\b', 'loads'),
        (r'\bcarregam\b', 'load'),
        (r'\bcarregar\b', 'to load'),
        (r'\bcarregaremos\b', 'we will load'),
        (r'\bcarregamos\b', 'we load'),
        (r'\bexecuta\b', 'executes'),
        (r'\bexecutam\b', 'execute'),
        (r'\bexecutar\b', 'to execute'),
        (r'\bexecutaremos\b', 'we will execute'),
        (r'\bexecutamos\b', 'we execute'),
        (r'\baplica\b', 'applies'),
        (r'\baplicam\b', 'apply'),
        (r'\baplicar\b', 'to apply'),
        (r'\baplicaremos\b', 'we will apply'),
        (r'\baplicamos\b', 'we apply'),
        (r'\bprocessa\b', 'processes'),
        (r'\bprocessam\b', 'process'),
        (r'\bprocessar\b', 'to process'),
        (r'\bprocessaremos\b', 'we will process'),
        (r'\bprocessamos\b', 'we process'),
        (r'\bcalcula\b', 'calculates'),
        (r'\bcalculam\b', 'calculate'),
        (r'\bcalcular\b', 'to calculate'),
        (r'\bcalcularemos\b', 'we will calculate'),
        (r'\bcalculamos\b', 'we calculate'),
        (r'\bdefine\b', 'defines'),
        (r'\bdefinem\b', 'define'),
        (r'\bdefinir\b', 'to define'),
        (r'\bdefiniremos\b', 'we will define'),
        (r'\bdefinimos\b', 'we define'),
        (r'\brepresenta\b', 'represents'),
        (r'\brepresentam\b', 'represent'),
        (r'\brepresentar\b', 'to represent'),
        (r'\brepresentaremos\b', 'we will represent'),
        (r'\brepresentamos\b', 'we represent'),
        (r'\brepresentando\b', 'representing'),
        (r'\bocorre\b', 'occurs'),
        (r'\bocorrem\b', 'occur'),
        (r'\bocorrer\b', 'to occur'),
        (r'\bocorrerá\b', 'will occur'),
        (r'\baumenta\b', 'increases'),
        (r'\baumentam\b', 'increase'),
        (r'\baumentar\b', 'to increase'),
        (r'\baumentará\b', 'will increase'),
        (r'\bmelhora\b', 'improves'),
        (r'\bmelhoram\b', 'improve'),
        (r'\bmelhorar\b', 'to improve'),
        (r'\bmelhorará\b', 'will improve'),
        (r'\bevidencia\b', 'shows'),
        (r'\bevidenciam\b', 'show'),
        (r'\bevidenciar\b', 'to show'),
        (r'\bevidenciarão\b', 'will show'),
        (r'\bcoleta\b', 'collects'),
        (r'\bcoletam\b', 'collect'),
        (r'\bcoletar\b', 'to collect'),
        (r'\bcoletaremos\b', 'we will collect'),
        (r'\bcoletando\b', 'collecting'),
        
        # Common nouns
        (r'\bseguinte\b', 'following'),
        (r'\bseguintes\b', 'following'),
        (r'\bsinal\b', 'signal'),
        (r'\bsinais\b', 'signals'),
        (r'\bamostra\b', 'sample'),
        (r'\bamostras\b', 'samples'),
        (r'\bfiltro\b', 'filter'),
        (r'\bfiltros\b', 'filters'),
        (r'\bgráfico\b', 'graph'),
        (r'\bgráficos\b', 'graphs'),
        (r'\bimagem\b', 'image'),
        (r'\bimagens\b', 'images'),
        (r'\bdado\b', 'data'),
        (r'\bdados\b', 'data'),
        (r'\bvalor\b', 'value'),
        (r'\bvalores\b', 'values'),
        (r'\bponto\b', 'point'),
        (r'\bpontos\b', 'points'),
        (r'\beixo\b', 'axis'),
        (r'\beixos\b', 'axes'),
        (r'\blinha\b', 'line'),
        (r'\blinhas\b', 'lines'),
        (r'\bmarcador\b', 'marker'),
        (r'\bmarcadores\b', 'markers'),
        (r'\bfrequência\b', 'frequency'),
        (r'\bfrequências\b', 'frequencies'),
        (r'\bamplitude\b', 'amplitude'),
        (r'\bamplitudes\b', 'amplitudes'),
        (r'\bfase\b', 'phase'),
        (r'\bfases\b', 'phases'),
        (r'\bperíodo\b', 'period'),
        (r'\bperíodos\b', 'periods'),
        (r'\bciclo\b', 'cycle'),
        (r'\bciclos\b', 'cycles'),
        (r'\btaxa\b', 'rate'),
        (r'\btaxas\b', 'rates'),
        (r'\btempo\b', 'time'),
        (r'\btempos\b', 'times'),
        (r'\binstante\b', 'instant'),
        (r'\binstantes\b', 'instants'),
        (r'\bmomento\b', 'moment'),
        (r'\bmomentos\b', 'moments'),
        (r'\bsequência\b', 'sequence'),
        (r'\bsequências\b', 'sequences'),
        (r'\bsérie\b', 'series'),
        (r'\bséries\b', 'series'),
        (r'\btransformada\b', 'transform'),
        (r'\btransformadas\b', 'transforms'),
        (r'\bconvolução\b', 'convolution'),
        (r'\bconvoluções\b', 'convolutions'),
        (r'\bcorrelação\b', 'correlation'),
        (r'\bcorrelações\b', 'correlations'),
        (r'\bespectro\b', 'spectrum'),
        (r'\bespectros\b', 'spectra'),
        (r'\bmatriz\b', 'matrix'),
        (r'\bmatrizes\b', 'matrices'),
        (r'\bvetor\b', 'vector'),
        (r'\bvetores\b', 'vectors'),
        (r'\barray\b', 'array'),
        (r'\barrays\b', 'arrays'),
        (r'\btítulo\b', 'title'),
        (r'\btítulos\b', 'titles'),
        (r'\blegenda\b', 'legend'),
        (r'\blegendas\b', 'legends'),
        (r'\bgrade\b', 'grid'),
        (r'\bgrades\b', 'grids'),
        (r'\bcor\b', 'color'),
        (r'\bcores\b', 'colors'),
        (r'\btamanho\b', 'size'),
        (r'\btamanhos\b', 'sizes'),
        (r'\blargura\b', 'width'),
        (r'\blarguras\b', 'widths'),
        (r'\baltura\b', 'height'),
        (r'\balturas\b', 'heights'),
        (r'\bcomprimento\b', 'length'),
        (r'\bcomprimentos\b', 'lengths'),
        (r'\bprofundidade\b', 'depth'),
        (r'\bprofundidades\b', 'depths'),
        (r'\bdimensão\b', 'dimension'),
        (r'\bdimensões\b', 'dimensions'),
        (r'\btipo\b', 'type'),
        (r'\btipos\b', 'types'),
        (r'\bforma\b', 'shape'),
        (r'\bformas\b', 'shapes'),
        (r'\bestrutura\b', 'structure'),
        (r'\bestruturas\b', 'structures'),
        (r'\bformato\b', 'format'),
        (r'\bformatos\b', 'formats'),
        (r'\bexemplo\b', 'example'),
        (r'\bexemplos\b', 'examples'),
        (r'\bexercício\b', 'exercise'),
        (r'\bexercícios\b', 'exercises'),
        (r'\bprática\b', 'practice'),
        (r'\bpráticas\b', 'practices'),
        (r'\btarefa\b', 'task'),
        (r'\btarefas\b', 'tasks'),
        (r'\batividade\b', 'activity'),
        (r'\batividades\b', 'activities'),
        (r'\btrabalho\b', 'work'),
        (r'\btrabalhos\b', 'works'),
        (r'\bprojeto\b', 'project'),
        (r'\bprojetos\b', 'projects'),
        (r'\bsistema\b', 'system'),
        (r'\bsistemas\b', 'systems'),
        (r'\bmétodo\b', 'method'),
        (r'\bmétodos\b', 'methods'),
        (r'\btécnica\b', 'technique'),
        (r'\btécnicas\b', 'techniques'),
        (r'\balgoritmo\b', 'algorithm'),
        (r'\balgoritmos\b', 'algorithms'),
        (r'\bprocesso\b', 'process'),
        (r'\bprocessos\b', 'processes'),
        (r'\bprocedimento\b', 'procedure'),
        (r'\bprocedimentos\b', 'procedures'),
        (r'\bretorno\b', 'return'),
        (r'\bretornos\b', 'returns'),
        (r'\bresultado\b', 'result'),
        (r'\bresultados\b', 'results'),
        (r'\bsaída\b', 'output'),
        (r'\bsaídas\b', 'outputs'),
        (r'\bentrada\b', 'input'),
        (r'\bentradas\b', 'inputs'),
        (r'\bparâmetro\b', 'parameter'),
        (r'\bparâmetros\b', 'parameters'),
        (r'\bargumento\b', 'argument'),
        (r'\bargumentos\b', 'arguments'),
        (r'\bfunção\b', 'function'),
        (r'\bfunções\b', 'functions'),
        (r'\bvariável\b', 'variable'),
        (r'\bvariáveis\b', 'variables'),
        (r'\bconstante\b', 'constant'),
        (r'\bconstantes\b', 'constants'),
        (r'\bclasse\b', 'class'),
        (r'\bclasses\b', 'classes'),
        (r'\bobjeto\b', 'object'),
        (r'\bobjetos\b', 'objects'),
        (r'\batributo\b', 'attribute'),
        (r'\batributos\b', 'attributes'),
        (r'\bpropriedade\b', 'property'),
        (r'\bpropriedades\b', 'properties'),
        (r'\barquivo\b', 'file'),
        (r'\barquivos\b', 'files'),
        (r'\bpasta\b', 'folder'),
        (r'\bpastas\b', 'folders'),
        (r'\bdiretório\b', 'directory'),
        (r'\bdiretórios\b', 'directories'),
        (r'\bcaminho\b', 'path'),
        (r'\bcaminhos\b', 'paths'),
        (r'\bnome\b', 'name'),
        (r'\bnomes\b', 'names'),
        (r'\bextensão\b', 'extension'),
        (r'\bextensões\b', 'extensions'),
        (r'\bbiblioteca\b', 'library'),
        (r'\bbibliotecas\b', 'libraries'),
        (r'\bmódulo\b', 'module'),
        (r'\bmódulos\b', 'modules'),
        (r'\bpacote\b', 'package'),
        (r'\bpacotes\b', 'packages'),
        (r'\bimportação\b', 'import'),
        (r'\bimportações\b', 'imports'),
        (r'\binstalação\b', 'installation'),
        (r'\binstalações\b', 'installations'),
        (r'\bconfiguração\b', 'configuration'),
        (r'\bconfigurações\b', 'configurations'),
        (r'\bopção\b', 'option'),
        (r'\bopções\b', 'options'),
        (r'\bparameter\b', 'parameter'),
        (r'\bparameters\b', 'parameters'),
        (r'\berro\b', 'error'),
        (r'\berros\b', 'errors'),
        (r'\baviso\b', 'warning'),
        (r'\bavisos\b', 'warnings'),
        (r'\bmensagem\b', 'message'),
        (r'\bmensagens\b', 'messages'),
        (r'\binformação\b', 'information'),
        (r'\binformações\b', 'information'),
        (r'\bdocumentação\b', 'documentation'),
        (r'\bdocumentações\b', 'documentation'),
        (r'\bcomentário\b', 'comment'),
        (r'\bcomentários\b', 'comments'),
        (r'\bdescrição\b', 'description'),
        (r'\bdescrições\b', 'descriptions'),
        (r'\bexplicação\b', 'explanation'),
        (r'\bexplicações\b', 'explanations'),
        (r'\bobjetivo\b', 'objective'),
        (r'\bobjetivos\b', 'objectives'),
        (r'\bmeta\b', 'goal'),
        (r'\bmetas\b', 'goals'),
        (r'\bfinalidade\b', 'purpose'),
        (r'\bfinalidades\b', 'purposes'),
        (r'\butilidade\b', 'utility'),
        (r'\butilidades\b', 'utilities'),
        (r'\buso\b', 'use'),
        (r'\busos\b', 'uses'),
        (r'\baplicação\b', 'application'),
        (r'\baplicações\b', 'applications'),
        (r'\bimplementação\b', 'implementation'),
        (r'\bimplementações\b', 'implementations'),
        (r'\bdesenvolvimento\b', 'development'),
        (r'\bdesenvolvimentos\b', 'developments'),
        (r'\bprogramação\b', 'programming'),
        (r'\bprogramações\b', 'programming'),
        (r'\bcódigo\b', 'code'),
        (r'\bcódigos\b', 'codes'),
        (r'\bscript\b', 'script'),
        (r'\bscripts\b', 'scripts'),
        (r'\bprograma\b', 'program'),
        (r'\bprogramas\b', 'programs'),
        (r'\bsoftware\b', 'software'),
        (r'\bsoftwares\b', 'software'),
        (r'\baplicativo\b', 'application'),
        (r'\baplicativos\b', 'applications'),
        (r'\bferramenta\b', 'tool'),
        (r'\bferramentas\b', 'tools'),
        (r'\butilitário\b', 'utility'),
        (r'\butilitários\b', 'utilities'),
        (r'\brecurso\b', 'resource'),
        (r'\brecursos\b', 'resources'),
        (r'\bmaterial\b', 'material'),
        (r'\bmateriais\b', 'materials'),
        (r'\bconteúdo\b', 'content'),
        (r'\bconteúdos\b', 'contents'),
        (r'\btexto\b', 'text'),
        (r'\btextos\b', 'texts'),
        (r'\bnúmero\b', 'number'),
        (r'\bnúmeros\b', 'numbers'),
        (r'\binteiro\b', 'integer'),
        (r'\binteiros\b', 'integers'),
        (r'\bflutuante\b', 'float'),
        (r'\bflutuantes\b', 'floats'),
        (r'\bdecimal\b', 'decimal'),
        (r'\bdecimais\b', 'decimals'),
        (r'\bfração\b', 'fraction'),
        (r'\bfrações\b', 'fractions'),
        (r'\bpercentagem\b', 'percentage'),
        (r'\bpercentagens\b', 'percentages'),
        (r'\bproporcão\b', 'proportion'),
        (r'\bproporções\b', 'proportions'),
        (r'\brazão\b', 'ratio'),
        (r'\brazões\b', 'ratios'),
        (r'\brelação\b', 'relation'),
        (r'\brelações\b', 'relations'),
        (r'\bcomparação\b', 'comparison'),
        (r'\bcomparações\b', 'comparisons'),
        (r'\bdiferença\b', 'difference'),
        (r'\bdiferenças\b', 'differences'),
        (r'\bsemelhança\b', 'similarity'),
        (r'\bsemelhanças\b', 'similarities'),
        (r'\bigualdade\b', 'equality'),
        (r'\bigualdades\b', 'equalities'),
        (r'\bdesigualdade\b', 'inequality'),
        (r'\bdesigualdades\b', 'inequalities'),
        (r'\bequivalência\b', 'equivalence'),
        (r'\bequivalências\b', 'equivalences'),
        (r'\bcorrespondência\b', 'correspondence'),
        (r'\bcorrespondências\b', 'correspondences'),
        (r'\bassociação\b', 'association'),
        (r'\bassociações\b', 'associations'),
        (r'\bconexão\b', 'connection'),
        (r'\bconexões\b', 'connections'),
        (r'\bligação\b', 'link'),
        (r'\bligações\b', 'links'),
        (r'\bvínculo\b', 'bond'),
        (r'\bvínculos\b', 'bonds'),
        (r'\brelacionamento\b', 'relationship'),
        (r'\brelacionamentos\b', 'relationships'),
        (r'\binteração\b', 'interaction'),
        (r'\binterações\b', 'interactions'),
        (r'\bcomunicação\b', 'communication'),
        (r'\bcomunicações\b', 'communications'),
        (r'\btransmissão\b', 'transmission'),
        (r'\btransmissões\b', 'transmissions'),
        (r'\brecepção\b', 'reception'),
        (r'\brecepções\b', 'receptions'),
        (r'\benvio\b', 'sending'),
        (r'\benvios\b', 'sendings'),
        (r'\brecebimento\b', 'receiving'),
        (r'\brecebimentos\b', 'receivings'),
        (r'\bentrega\b', 'delivery'),
        (r'\bentregas\b', 'deliveries'),
        (r'\bdistribuição\b', 'distribution'),
        (r'\bdistribuições\b', 'distributions'),
        (r'\balocação\b', 'allocation'),
        (r'\balocações\b', 'allocations'),
        (r'\batribuição\b', 'attribution'),
        (r'\batribuições\b', 'attributions'),
        (r'\bdesignação\b', 'designation'),
        (r'\bdesignações\b', 'designations'),
        (r'\bnomeação\b', 'nomination'),
        (r'\bnomeações\b', 'nominations'),
        (r'\bidentificação\b', 'identification'),
        (r'\bidentificações\b', 'identifications'),
        (r'\breconhecimento\b', 'recognition'),
        (r'\breconhecimentos\b', 'recognitions'),
        (r'\bdetecção\b', 'detection'),
        (r'\bdetecções\b', 'detections'),
        (r'\blocalizaão\b', 'location'),
        (r'\blocalizações\b', 'locations'),
        (r'\bposição\b', 'position'),
        (r'\bposições\b', 'positions'),
        (r'\bcolocação\b', 'placement'),
        (r'\bcolocações\b', 'placements'),
        (r'\borientação\b', 'orientation'),
        (r'\borientações\b', 'orientations'),
        (r'\bdireção\b', 'direction'),
        (r'\bdireções\b', 'directions'),
        (r'\bsentido\b', 'sense'),
        (r'\bsentidos\b', 'senses'),
        (r'\bdeslocamento\b', 'displacement'),
        (r'\bdeslocamentos\b', 'displacements'),
        (r'\bmovimento\b', 'movement'),
        (r'\bmovimentos\b', 'movements'),
        (r'\bmovimentação\b', 'motion'),
        (r'\bmovimentações\b', 'motions'),
        (r'\btransporte\b', 'transport'),
        (r'\btransportes\b', 'transports'),
        (r'\btransferência\b', 'transfer'),
        (r'\btransferências\b', 'transfers'),
        (r'\bmudança\b', 'change'),
        (r'\bmudanças\b', 'changes'),
        (r'\balteração\b', 'alteration'),
        (r'\balterações\b', 'alterations'),
        (r'\bmodificação\b', 'modification'),
        (r'\bmodificações\b', 'modifications'),
        (r'\btransformação\b', 'transformation'),
        (r'\btransformações\b', 'transformations'),
        (r'\bconversão\b', 'conversion'),
        (r'\bconversões\b', 'conversions'),
        (r'\badaptação\b', 'adaptation'),
        (r'\badaptações\b', 'adaptations'),
        (r'\bajuste\b', 'adjustment'),
        (r'\bajustes\b', 'adjustments'),
        (r'\bcorreção\b', 'correction'),
        (r'\bcorreções\b', 'corrections'),
        (r'\bmelhoramento\b', 'improvement'),
        (r'\bmelhoramentos\b', 'improvements'),
        (r'\baperfeiçoamento\b', 'enhancement'),
        (r'\baperfeiçoamentos\b', 'enhancements'),
        (r'\botimização\b', 'optimization'),
        (r'\botimizações\b', 'optimizations'),
        (r'\bmaximização\b', 'maximization'),
        (r'\bmaximizações\b', 'maximizations'),
        (r'\bminimização\b', 'minimization'),
        (r'\bminimizações\b', 'minimizations'),
        (r'\bredução\b', 'reduction'),
        (r'\breduções\b', 'reductions'),
        (r'\bdiminuição\b', 'decrease'),
        (r'\bdiminuições\b', 'decreases'),
        (r'\baumento\b', 'increase'),
        (r'\baumentos\b', 'increases'),
        (r'\bcrescimento\b', 'growth'),
        (r'\bcrescimentos\b', 'growths'),
        (r'\bexpansão\b', 'expansion'),
        (r'\bexpansões\b', 'expansions'),
        (r'\bampliação\b', 'amplification'),
        (r'\bampliações\b', 'amplifications'),
        (r'\bextensão\b', 'extension'),
        (r'\bextensões\b', 'extensions'),
        (r'\bprolongamento\b', 'prolongation'),
        (r'\bprolongamentos\b', 'prolongations'),
        (r'\bcontinuação\b', 'continuation'),
        (r'\bcontinuações\b', 'continuations'),
        (r'\bprosseguimento\b', 'continuation'),
        (r'\bprosseguimentos\b', 'continuations'),
        (r'\bsequenciamento\b', 'sequencing'),
        (r'\bsequenciamentos\b', 'sequencings'),
        (r'\bordenação\b', 'ordering'),
        (r'\bordenações\b', 'orderings'),
        (r'\bclassificação\b', 'classification'),
        (r'\bclassificações\b', 'classifications'),
        (r'\bcategorização\b', 'categorization'),
        (r'\bcategorizações\b', 'categorizations'),
        (r'\bagrupamento\b', 'grouping'),
        (r'\bagrupamentos\b', 'groupings'),
        (r'\bseparação\b', 'separation'),
        (r'\bseparações\b', 'separations'),
        (r'\bdivisão\b', 'division'),
        (r'\bdivisões\b', 'divisions'),
        (r'\bpartição\b', 'partition'),
        (r'\bpartições\b', 'partitions'),
        (r'\bsegmentação\b', 'segmentation'),
        (r'\bsegmentações\b', 'segmentations'),
        (r'\bfragmentação\b', 'fragmentation'),
        (r'\bfragmentações\b', 'fragmentations'),
        (r'\bdecomposição\b', 'decomposition'),
        (r'\bdecomposições\b', 'decompositions'),
        (r'\bfatoração\b', 'factorization'),
        (r'\bfatorações\b', 'factorizations'),
        (r'\bsimplificação\b', 'simplification'),
        (r'\bsimplificações\b', 'simplifications'),
        (r'\bcomplexificação\b', 'complexification'),
        (r'\bcomplexificações\b', 'complexifications'),
        (r'\bcomplicação\b', 'complication'),
        (r'\bcomplicações\b', 'complications'),
        (r'\bdifficuldade\b', 'difficulty'),
        (r'\bdifficuldades\b', 'difficulties'),
        (r'\bfacilidade\b', 'facility'),
        (r'\bfacilidades\b', 'facilities'),
        (r'\bsimplicidade\b', 'simplicity'),
        (r'\bsimplicidades\b', 'simplicities'),
        (r'\bcomplexidade\b', 'complexity'),
        (r'\bcomplexidades\b', 'complexities'),
        (r'\beficiência\b', 'efficiency'),
        (r'\beficiências\b', 'efficiencies'),
        (r'\beficácia\b', 'efficacy'),
        (r'\beficácias\b', 'efficacies'),
        (r'\befetividade\b', 'effectiveness'),
        (r'\befetividades\b', 'effectiveness'),
        (r'\bdesempenho\b', 'performance'),
        (r'\bdesempenhos\b', 'performances'),
        (r'\brendimento\b', 'yield'),
        (r'\brendimentos\b', 'yields'),
        (r'\bprodutividade\b', 'productivity'),
        (r'\bprodutividades\b', 'productivities'),
        (r'\bcapacidade\b', 'capacity'),
        (r'\bcapacidades\b', 'capacities'),
        (r'\bhabilidade\b', 'ability'),
        (r'\bhabilidades\b', 'abilities'),
        (r'\bcompetência\b', 'competence'),
        (r'\bcompetências\b', 'competences'),
        (r'\bqualidade\b', 'quality'),
        (r'\bqualidades\b', 'qualities'),
        (r'\bquantidade\b', 'quantity'),
        (r'\bquantidades\b', 'quantities'),
        (r'\bcaracterística\b', 'characteristic'),
        (r'\bcaracterísticas\b', 'characteristics'),
        (r'\bpropriedade\b', 'property'),
        (r'\bpropriedades\b', 'properties'),
        (r'\batributo\b', 'attribute'),
        (r'\batributos\b', 'attributes'),
        (r'\baspecto\b', 'aspect'),
        (r'\baspectos\b', 'aspects'),
        (r'\belemento\b', 'element'),
        (r'\belementos\b', 'elements'),
        (r'\bcomponente\b', 'component'),
        (r'\bcomponentes\b', 'components'),
        (r'\bparte\b', 'part'),
        (r'\bpartes\b', 'parts'),
        (r'\bpedaço\b', 'piece'),
        (r'\bpedaços\b', 'pieces'),
        (r'\bfragmento\b', 'fragment'),
        (r'\bfragmentos\b', 'fragments'),
        (r'\bporção\b', 'portion'),
        (r'\bporções\b', 'portions'),
        (r'\bseção\b', 'section'),
        (r'\bseções\b', 'sections'),
        (r'\bsegmento\b', 'segment'),
        (r'\bsegmentos\b', 'segments'),
        (r'\bsubdivisão\b', 'subdivision'),
        (r'\bsubdivisões\b', 'subdivisions'),
        (r'\bsubconjunto\b', 'subset'),
        (r'\bsubconjuntos\b', 'subsets'),
        (r'\bconjunto\b', 'set'),
        (r'\bconjuntos\b', 'sets'),
        (r'\bgrupo\b', 'group'),
        (r'\bgrupos\b', 'groups'),
        (r'\bcoleção\b', 'collection'),
        (r'\bcoleções\b', 'collections'),
        (r'\bagrupação\b', 'gathering'),
        (r'\bagrupações\b', 'gatherings'),
        (r'\bcomilação\b', 'compilation'),
        (r'\bcomilações\b', 'compilations'),
        (r'\breunião\b', 'meeting'),
        (r'\breuniões\b', 'meetings'),
        (r'\benjunto\b', 'together'),
        (r'\bseparado\b', 'separate'),
        (r'\bseparados\b', 'separate'),
        (r'\bseparada\b', 'separate'),
        (r'\bseparadas\b', 'separate'),
        (r'\bindividual\b', 'individual'),
        (r'\bindividuais\b', 'individual'),
        (r'\bparticular\b', 'particular'),
        (r'\bparticulares\b', 'particular'),
        (r'\bespecífico\b', 'specific'),
        (r'\bespecíficos\b', 'specific'),
        (r'\bespecífica\b', 'specific'),
        (r'\bespecíficas\b', 'specific'),
        (r'\bgeral\b', 'general'),
        (r'\bgerais\b', 'general'),
        (r'\buniversal\b', 'universal'),
        (r'\buniversais\b', 'universal'),
        (r'\bcomum\b', 'common'),
        (r'\bcomuns\b', 'common'),
        (r'\bnormal\b', 'normal'),
        (r'\bnormais\b', 'normal'),
        (r'\bpadrão\b', 'standard'),
        (r'\bpadrões\b', 'standards'),
        (r'\bmodelo\b', 'model'),
        (r'\bmodelos\b', 'models'),
        (r'\bparadigma\b', 'paradigm'),
        (r'\bparadigmas\b', 'paradigms'),
        (r'\breferência\b', 'reference'),
        (r'\breferências\b', 'references'),
        (r'\bbenchmark\b', 'benchmark'),
        (r'\bbenchmarks\b', 'benchmarks'),
        (r'\bbase\b', 'base'),
        (r'\bbases\b', 'bases'),
        (r'\bfundamento\b', 'foundation'),
        (r'\bfundamentos\b', 'foundations'),
        (r'\bfundação\b', 'foundation'),
        (r'\bfundações\b', 'foundations'),
        (r'\balicerce\b', 'foundation'),
        (r'\balicerces\b', 'foundations'),
        (r'\bsuporte\b', 'support'),
        (r'\bsuportes\b', 'supports'),
        (r'\bapoio\b', 'support'),
        (r'\bapoios\b', 'supports'),
        (r'\bsustento\b', 'sustenance'),
        (r'\bsustentos\b', 'sustenances'),
        (r'\bsustentação\b', 'sustentation'),
        (r'\bsustentações\b', 'sustentations'),
        (r'\bmanutenção\b', 'maintenance'),
        (r'\bmanutenções\b', 'maintenances'),
        (r'\bconservação\b', 'conservation'),
        (r'\bconservações\b', 'conservations'),
        (r'\bpreservação\b', 'preservation'),
        (r'\bpreservações\b', 'preservations'),
        (r'\bprotecção\b', 'protection'),
        (r'\bprotecções\b', 'protections'),
        (r'\bsegurança\b', 'security'),
        (r'\bseguranças\b', 'securities'),
        (r'\bgarantia\b', 'guarantee'),
        (r'\bgarantias\b', 'guarantees'),
        (r'\bcerteza\b', 'certainty'),
        (r'\bcertezas\b', 'certainties'),
        (r'\bseguridade\b', 'surety'),
        (r'\bseguridades\b', 'sureties'),
        (r'\bconfiança\b', 'confidence'),
        (r'\bconfianças\b', 'confidences'),
        (r'\bconfiabilidade\b', 'reliability'),
        (r'\bconfiabilidades\b', 'reliabilities'),
        (r'\bfidelidade\b', 'fidelity'),
        (r'\bfidelidades\b', 'fidelities'),
        (r'\bprecisão\b', 'precision'),
        (r'\bprecisões\b', 'precisions'),
        (r'\bexatidão\b', 'accuracy'),
        (r'\bexatidões\b', 'accuracies'),
        (r'\bcorreção\b', 'correctness'),
        (r'\bcorreções\b', 'correctnesses'),
        (r'\bveracidade\b', 'veracity'),
        (r'\bveracidades\b', 'veracities'),
        (r'\bautenticidade\b', 'authenticity'),
        (r'\bautenticidades\b', 'authenticities'),
        (r'\bvalidação\b', 'validation'),
        (r'\bvalidações\b', 'validations'),
        (r'\bverificação\b', 'verification'),
        (r'\bverificações\b', 'verifications'),
        (r'\bcomprovação\b', 'verification'),
        (r'\bcomprovações\b', 'verifications'),
        (r'\bconfirmação\b', 'confirmation'),
        (r'\bconfirmações\b', 'confirmations'),
        (r'\batestação\b', 'attestation'),
        (r'\batestações\b', 'attestations'),
        (r'\bcertificação\b', 'certification'),
        (r'\bcertificações\b', 'certifications'),
        (r'\bhomologação\b', 'homologation'),
        (r'\bhomologações\b', 'homologations'),
        (r'\baprovação\b', 'approval'),
        (r'\baprovações\b', 'approvals'),
        (r'\baceitação\b', 'acceptance'),
        (r'\baceitações\b', 'acceptances'),
        (r'\bconcordância\b', 'agreement'),
        (r'\bconcordâncias\b', 'agreements'),
        (r'\bassentimento\b', 'assent'),
        (r'\bassentimentos\b', 'assents'),
        (r'\bconsentimento\b', 'consent'),
        (r'\bconsentimentos\b', 'consents'),
        (r'\bpermissão\b', 'permission'),
        (r'\bpermissões\b', 'permissions'),
        (r'\bautorização\b', 'authorization'),
        (r'\bautorizações\b', 'authorizations'),
        (r'\blicença\b', 'license'),
        (r'\blicenças\b', 'licenses'),
        (r'\bcredencial\b', 'credential'),
        (r'\bcredenciais\b', 'credentials'),
        (r'\bcertificado\b', 'certificate'),
        (r'\bcertificados\b', 'certificates'),
        (r'\bdiploma\b', 'diploma'),
        (r'\bdiplomas\b', 'diplomas'),
        (r'\btítulo\b', 'title'),
        (r'\btítulos\b', 'titles'),
        (r'\bgrau\b', 'degree'),
        (r'\bgraus\b', 'degrees'),
        (r'\bnível\b', 'level'),
        (r'\bníveis\b', 'levels'),
        (r'\bestágio\b', 'stage'),
        (r'\bestágios\b', 'stages'),
        (r'\bfase\b', 'phase'),
        (r'\bfases\b', 'phases'),
        (r'\betapa\b', 'step'),
        (r'\betapas\b', 'steps'),
        (r'\bpasso\b', 'step'),
        (r'\bpassos\b', 'steps'),
        (r'\bmomento\b', 'moment'),
        (r'\bmomentos\b', 'moments'),
        (r'\binstante\b', 'instant'),
        (r'\binstantes\b', 'instants'),
        (r'\bperíodo\b', 'period'),
        (r'\bperíodos\b', 'periods'),
        (r'\bintervalo\b', 'interval'),
        (r'\bintervalos\b', 'intervals'),
        (r'\bduração\b', 'duration'),
        (r'\bdurações\b', 'durations'),
        (r'\btempo\b', 'time'),
        (r'\btempos\b', 'times'),
        (r'\bépoca\b', 'epoch'),
        (r'\bépocas\b', 'epochs'),
        (r'\bera\b', 'era'),
        (r'\beras\b', 'eras'),
        (r'\bidade\b', 'age'),
        (r'\bidades\b', 'ages'),
        (r'\bgeração\b', 'generation'),
        (r'\bgerações\b', 'generations'),
        (r'\bversão\b', 'version'),
        (r'\bversões\b', 'versions'),
        (r'\bedição\b', 'edition'),
        (r'\bedições\b', 'editions'),
        (r'\breviewing\b', 'revision'),
        (r'\brevisões\b', 'revisions'),
        (r'\batualização\b', 'update'),
        (r'\batualizações\b', 'updates'),
        (r'\bupgrade\b', 'upgrade'),
        (r'\bupgrades\b', 'upgrades'),
        (r'\bmelhoramento\b', 'improvement'),
        (r'\bmelhoramentos\b', 'improvements'),
        (r'\baperfeiçoamento\b', 'enhancement'),
        (r'\baperfeiçoamentos\b', 'enhancements'),
        (r'\botimização\b', 'optimization'),
        (r'\botimizações\b', 'optimizations'),
        (r'\brefinamento\b', 'refinement'),
        (r'\brefinamentos\b', 'refinements'),
        (r'\bajustamento\b', 'adjustment'),
        (r'\bajustamentos\b', 'adjustments'),
        (r'\bcalibração\b', 'calibration'),
        (r'\bcalibrações\b', 'calibrations'),
        (r'\bsintonia\b', 'tuning'),
        (r'\bsintonias\b', 'tunings'),
        (r'\bajuste fino\b', 'fine tuning'),
        (r'\bajustes finos\b', 'fine tunings'),
        (r'\bconfiguração\b', 'configuration'),
        (r'\bconfigurações\b', 'configurations'),
        (r'\bparametrização\b', 'parameterization'),
        (r'\bparametrizações\b', 'parameterizations'),
        (r'\bpersonalização\b', 'customization'),
        (r'\bpersonalizações\b', 'customizations'),
        (r'\bcustomização\b', 'customization'),
        (r'\bcustomizações\b', 'customizations'),
        (r'\badaptação\b', 'adaptation'),
        (r'\badaptações\b', 'adaptations'),
        (r'\bmoldagem\b', 'molding'),
        (r'\bmoldagens\b', 'moldings'),
        (r'\bmodulação\b', 'modulation'),
        (r'\bmodulações\b', 'modulations'),
        (r'\bvariação\b', 'variation'),
        (r'\bvariações\b', 'variations'),
        (r'\bfluctuação\b', 'fluctuation'),
        (r'\bfluctuações\b', 'fluctuations'),
        (r'\boscilação\b', 'oscillation'),
        (r'\boscilações\b', 'oscillations'),
        (r'\bvibração\b', 'vibration'),
        (r'\bvibrações\b', 'vibrations'),
        (r'\btremor\b', 'tremor'),
        (r'\btremores\b', 'tremors'),
        (r'\babalo\b', 'shake'),
        (r'\babalos\b', 'shakes'),
        (r'\bchoque\b', 'shock'),
        (r'\bchoques\b', 'shocks'),
        (r'\bimpacto\b', 'impact'),
        (r'\bimpactos\b', 'impacts'),
        (r'\bcolisão\b', 'collision'),
        (r'\bcolisões\b', 'collisions'),
        (r'\bencontro\b', 'encounter'),
        (r'\bencontros\b', 'encounters'),
        (r'\bintersecção\b', 'intersection'),
        (r'\bintersecções\b', 'intersections'),
        (r'\bcruzamento\b', 'crossing'),
        (r'\bcruzamentos\b', 'crossings'),
        (r'\binterseção\b', 'intersection'),
        (r'\binterseções\b', 'intersections'),
        (r'\bunião\b', 'union'),
        (r'\buniões\b', 'unions'),
        (r'\bjunção\b', 'junction'),
        (r'\bjunções\b', 'junctions'),
        (r'\bfusão\b', 'fusion'),
        (r'\bfusões\b', 'fusions'),
        (r'\bmescla\b', 'merge'),
        (r'\bmesclas\b', 'merges'),
        (r'\bmistura\b', 'mixture'),
        (r'\bmisturas\b', 'mixtures'),
        (r'\bcombinação\b', 'combination'),
        (r'\bcombinações\b', 'combinations'),
        (r'\bcomposição\b', 'composition'),
        (r'\bcomposições\b', 'compositions'),
        (r'\barranjo\b', 'arrangement'),
        (r'\barranjos\b', 'arrangements'),
        (r'\bpermutação\b', 'permutation'),
        (r'\bpermutações\b', 'permutations'),
        (r'\bvariação\b', 'variation'),
        (r'\bvariações\b', 'variations'),
        (r'\bseleção\b', 'selection'),
        (r'\bseleções\b', 'selections'),
        (r'\bescolha\b', 'choice'),
        (r'\bescolhas\b', 'choices'),
        (r'\bopção\b', 'option'),
        (r'\bopções\b', 'options'),
        (r'\balternativa\b', 'alternative'),
        (r'\balternativas\b', 'alternatives'),
        (r'\bpossibilidade\b', 'possibility'),
        (r'\bpossibilidades\b', 'possibilities'),
        (r'\bpotencial\b', 'potential'),
        (r'\bpotenciais\b', 'potentials'),
        (r'\bcapacidade\b', 'capacity'),
        (r'\bcapacidades\b', 'capacities'),
        (r'\bpotência\b', 'power'),
        (r'\bpotências\b', 'powers'),
        (r'\bforça\b', 'force'),
        (r'\bforças\b', 'forces'),
        (r'\benergia\b', 'energy'),
        (r'\benergias\b', 'energies'),
        (r'\bvigor\b', 'vigor'),
        (r'\bvigores\b', 'vigors'),
        (r'\brobustez\b', 'robustness'),
        (r'\brobustezas\b', 'robustnesses'),
        (r'\bresistência\b', 'resistance'),
        (r'\bresistências\b', 'resistances'),
        (r'\bdurabilidade\b', 'durability'),
        (r'\bdurabilidades\b', 'durabilities'),
        (r'\bpermanência\b', 'permanence'),
        (r'\bpermanências\b', 'permanences'),
        (r'\bestabilidade\b', 'stability'),
        (r'\bestabilidades\b', 'stabilities'),
        (r'\bequilíbrio\b', 'equilibrium'),
        (r'\bequilíbrios\b', 'equilibria'),
        (r'\bbalanço\b', 'balance'),
        (r'\bbalanços\b', 'balances'),
        (r'\bharmonia\b', 'harmony'),
        (r'\bharmonias\b', 'harmonies'),
        (r'\bsimetria\b', 'symmetry'),
        (r'\bsimetrias\b', 'symmetries'),
        (r'\bproporcionalidade\b', 'proportionality'),
        (r'\bproporcionalidades\b', 'proportionalities'),
        (r'\buniformidade\b', 'uniformity'),
        (r'\buniformidades\b', 'uniformities'),
        (r'\bhomogeneidade\b', 'homogeneity'),
        (r'\bhomogeneidades\b', 'homogeneities'),
        (r'\bconsistência\b', 'consistency'),
        (r'\bconsistências\b', 'consistencies'),
        (r'\bcoerência\b', 'coherence'),
        (r'\bcoerências\b', 'coherences'),
        (r'\blogicidade\b', 'logicality'),
        (r'\blogicidades\b', 'logicalities'),
        (r'\bracionalidade\b', 'rationality'),
        (r'\bracionalidades\b', 'rationalities'),
        (r'\brazoabilidade\b', 'reasonableness'),
        (r'\brazoabilidades\b', 'reasonablenesses'),
        (r'\bsensatez\b', 'sensibility'),
        (r'\bsensatezes\b', 'sensibilities'),
        (r'\bprudência\b', 'prudence'),
        (r'\bprudências\b', 'prudences'),
        (r'\bcautela\b', 'caution'),
        (r'\bcautelas\b', 'cautions'),
        (r'\bcuidado\b', 'care'),
        (r'\bcuidados\b', 'cares'),
        (r'\batenção\b', 'attention'),
        (r'\batenções\b', 'attentions'),
        (r'\bfoco\b', 'focus'),
        (r'\bfocos\b', 'focuses'),
        (r'\bconcentração\b', 'concentration'),
        (r'\bconcentrações\b', 'concentrations'),
        (r'\bdedicação\b', 'dedication'),
        (r'\bdedicações\b', 'dedications'),
        (r'\bempenho\b', 'commitment'),
        (r'\bempenhos\b', 'commitments'),
        (r'\besforço\b', 'effort'),
        (r'\besforços\b', 'efforts'),
        (r'\btentativa\b', 'attempt'),
        (r'\btentativas\b', 'attempts'),
        (r'\bexperimento\b', 'experiment'),
        (r'\bexperimentos\b', 'experiments'),
        (r'\bexperiência\b', 'experience'),
        (r'\bexperiências\b', 'experiences'),
        (r'\bprática\b', 'practice'),
        (r'\bpráticas\b', 'practices'),
        (r'\bexercício\b', 'exercise'),
        (r'\bexercícios\b', 'exercises'),
        (r'\btreinamento\b', 'training'),
        (r'\btreinamentos\b', 'trainings'),
        (r'\bcapacitação\b', 'training'),
        (r'\bcapacitações\b', 'trainings'),
        (r'\bqualificação\b', 'qualification'),
        (r'\bqualificações\b', 'qualifications'),
        (r'\bformação\b', 'formation'),
        (r'\bformações\b', 'formations'),
        (r'\beducação\b', 'education'),
        (r'\beducações\b', 'educations'),
        (r'\bensino\b', 'teaching'),
        (r'\bensinos\b', 'teachings'),
        (r'\baprendizado\b', 'learning'),
        (r'\baprendizados\b', 'learnings'),
        (r'\baprendizagem\b', 'learning'),
        (r'\baprendizagens\b', 'learnings'),
        (r'\bconhecimento\b', 'knowledge'),
        (r'\bconhecimentos\b', 'knowledge'),
        (r'\bsaber\b', 'knowing'),
        (r'\bsaberes\b', 'knowledge'),
        (r'\bsabedoria\b', 'wisdom'),
        (r'\bsabedorias\b', 'wisdoms'),
        (r'\binteligência\b', 'intelligence'),
        (r'\binteligências\b', 'intelligences'),
        (r'\bcompreensão\b', 'comprehension'),
        (r'\bcompreensões\b', 'comprehensions'),
        (r'\bentendimento\b', 'understanding'),
        (r'\bentendimentos\b', 'understandings'),
        (r'\binsight\b', 'insight'),
        (r'\binsights\b', 'insights'),
        (r'\bpercepção\b', 'perception'),
        (r'\bpercepções\b', 'perceptions'),
        (r'\bvisão\b', 'vision'),
        (r'\bvisões\b', 'visions'),
        (r'\bperspectiva\b', 'perspective'),
        (r'\bperspectivas\b', 'perspectives'),
        (r'\bângulo\b', 'angle'),
        (r'\bângulos\b', 'angles'),
        (r'\bponteiro de vista\b', 'point of view'),
        (r'\bponteiros de vista\b', 'points of view'),
        (r'\bponto de vista\b', 'point of view'),
        (r'\bpontos de vista\b', 'points of view'),
        (r'\bopinião\b', 'opinion'),
        (r'\bopiniões\b', 'opinions'),
        (r'\bparecer\b', 'opinion'),
        (r'\bpareceres\b', 'opinions'),
        (r'\bjuízo\b', 'judgment'),
        (r'\bjuízos\b', 'judgments'),
        (r'\bavaliação\b', 'evaluation'),
        (r'\bavaliações\b', 'evaluations'),
        (r'\bjulgamento\b', 'judgment'),
        (r'\bjulgamentos\b', 'judgments'),
        (r'\bapreciação\b', 'appreciation'),
        (r'\bapreciações\b', 'appreciations'),
        (r'\banálise\b', 'analysis'),
        (r'\banálises\b', 'analyses'),
        (r'\bexame\b', 'examination'),
        (r'\bexames\b', 'examinations'),
        (r'\binspeção\b', 'inspection'),
        (r'\binspeções\b', 'inspections'),
        (r'\brevisão\b', 'revision'),
        (r'\brevisões\b', 'revisions'),
        (r'\baviso\b', 'notice'),
        (r'\bavisos\b', 'notices'),
        (r'\bmensagem\b', 'message'),
        (r'\bmensagens\b', 'messages'),
        (r'\bcomunicado\b', 'communication'),
        (r'\bcomunicados\b', 'communications'),
        (r'\bnotificação\b', 'notification'),
        (r'\bnotificações\b', 'notifications'),
        (r'\balerta\b', 'alert'),
        (r'\balertas\b', 'alerts'),
        (r'\balarme\b', 'alarm'),
        (r'\balarmes\b', 'alarms'),
        (r'\bsinal de alerta\b', 'warning signal'),
        (r'\bsinais de alerta\b', 'warning signals'),
        (r'\bindício\b', 'indication'),
        (r'\bindícios\b', 'indications'),
        (r'\bevulaência\b', 'evidence'),
        (r'\bevulaências\b', 'evidences'),
        (r'\bprova\b', 'proof'),
        (r'\bprovas\b', 'proofs'),
        (r'\bcomprovante\b', 'voucher'),
        (r'\bcomprovantes\b', 'vouchers'),
        (r'\batestado\b', 'certificate'),
        (r'\batestados\b', 'certificates'),
        (r'\bcertidão\b', 'certificate'),
        (r'\bcertidões\b', 'certificates'),
        (r'\bdocumento\b', 'document'),
        (r'\bdocumentos\b', 'documents'),
        (r'\bregistro\b', 'record'),
        (r'\bregistros\b', 'records'),
        (r'\banotação\b', 'annotation'),
        (r'\banotações\b', 'annotations'),
        (r'\bobservação\b', 'observation'),
        (r'\bobservações\b', 'observations'),
        (r'\bnota\b', 'note'),
        (r'\bnotas\b', 'notes'),
        (r'\breminder\b', 'reminder'),
        (r'\breminders\b', 'reminders'),
        (r'\blembrete\b', 'reminder'),
        (r'\blembretes\b', 'reminders'),
        (r'\baviso\b', 'warning'),
        (r'\bavisos\b', 'warnings'),
        (r'\blembrar\b', 'remember'),
        (r'\blembrança\b', 'remembrance'),
        (r'\blembranças\b', 'remembrances'),
        (r'\bmemória\b', 'memory'),
        (r'\bmemórias\b', 'memories'),
        (r'\brecordação\b', 'recollection'),
        (r'\brecordações\b', 'recollections'),
        (r'\brevocação\b', 'recall'),
        (r'\brevocações\b', 'recalls'),
        (r'\brecuperação\b', 'recovery'),
        (r'\brecuperações\b', 'recoveries'),
        (r'\bresgate\b', 'rescue'),
        (r'\bresgates\b', 'rescues'),
        (r'\bsalvamento\b', 'rescue'),
        (r'\bsalvamentos\b', 'rescues'),
        (r'\brestauração\b', 'restoration'),
        (r'\brestaurações\b', 'restorations'),
        (r'\breestablecimento\b', 'reestablishment'),
        (r'\breestablecimentos\b', 'reestablishments'),
        (r'\brestituição\b', 'restitution'),
        (r'\brestituições\b', 'restitutions'),
        (r'\bdevolvção\b', 'return'),
        (r'\bdevolvções\b', 'returns'),
        (r'\bretorno\b', 'return'),
        (r'\bretornos\b', 'returns'),
        (r'\bvolta\b', 'return'),
        (r'\bvoltas\b', 'returns'),
        (r'\brегresso\b', 'return'),
        (r'\brеgressos\b', 'returns'),
        (r'\bida\b', 'going'),
        (r'\bidas\b', 'goings'),
        (r'\bvinda\b', 'coming'),
        (r'\bvindas\b', 'comings'),
        (r'\bchegada\b', 'arrival'),
        (r'\bchegadas\b', 'arrivals'),
        (r'\bpartida\b', 'departure'),
        (r'\bpartidas\b', 'departures'),
        (r'\bsaída\b', 'exit'),
        (r'\bsaídas\b', 'exits'),
        (r'\bentrada\b', 'entrance'),
        (r'\bentradas\b', 'entrances'),
        (r'\bacesso\b', 'access'),
        (r'\bacessos\b', 'accesses'),
        (r'\bporta\b', 'door'),
        (r'\bportas\b', 'doors'),
        (r'\bportão\b', 'gate'),
        (r'\bportões\b', 'gates'),
        (r'\bcancela\b', 'gate'),
        (r'\bcancelas\b', 'gates'),
        (r'\bbarreira\b', 'barrier'),
        (r'\bbarreiras\b', 'barriers'),
        (r'\bobstáculo\b', 'obstacle'),
        (r'\bobstáculos\b', 'obstacles'),
        (r'\bimpedimento\b', 'impediment'),
        (r'\bimpedimentos\b', 'impediments'),
        (r'\bestorvo\b', 'hindrance'),
        (r'\bestorvos\b', 'hindrances'),
        (r'\batrapalhation\b', 'hindrance'),
        (r'\batrapalhations\b', 'hindrances'),
        (r'\bdifficuldade\b', 'difficulty'),
        (r'\bdifficuldades\b', 'difficulties'),
        (r'\bproblema\b', 'problem'),
        (r'\bproblemas\b', 'problems'),
        (r'\bquestão\b', 'question'),
        (r'\bquestões\b', 'questions'),
        (r'\bdúvida\b', 'doubt'),
        (r'\bdúvidas\b', 'doubts'),
        (r'\binterrogação\b', 'interrogation'),
        (r'\binterrogações\b', 'interrogations'),
        (r'\bpergunta\b', 'question'),
        (r'\bperguntas\b', 'questions'),
        (r'\bindagação\b', 'inquiry'),
        (r'\bindagações\b', 'inquiries'),
        (r'\bconsulta\b', 'query'),
        (r'\bconsultas\b', 'queries'),
        (r'\bquestion\b', 'question'),
        (r'\bquestions\b', 'questions'),
        (r'\bresposta\b', 'answer'),
        (r'\brespostas\b', 'answers'),
        (r'\breplica\b', 'reply'),
        (r'\breplicas\b', 'replies'),
        (r'\bretorno\b', 'return'),
        (r'\bretornos\b', 'returns'),
        (r'\bfeedback\b', 'feedback'),
        (r'\bfeedbacks\b', 'feedbacks'),
        (r'\bretroalimentação\b', 'feedback'),
        (r'\bretroalimentações\b', 'feedbacks'),
        (r'\bretorno\b', 'return'),
        (r'\bretornos\b', 'returns'),
        (r'\breação\b', 'reaction'),
        (r'\breações\b', 'reactions'),
        (r'\bresposta\b', 'response'),
        (r'\brespostas\b', 'responses'),
        (r'\bcorrespondência\b', 'correspondence'),
        (r'\bcorrespondências\b', 'correspondences'),
        (r'\breciprocidade\b', 'reciprocity'),
        (r'\breciprocidades\b', 'reciprocities'),
        (r'\bmutualidade\b', 'mutuality'),
        (r'\bmutualidades\b', 'mutualities'),
        (r'\bintercâmbio\b', 'exchange'),
        (r'\bintercâmbios\b', 'exchanges'),
        (r'\bpermuta\b', 'exchange'),
        (r'\bpermutas\b', 'exchanges'),
        (r'\btroca\b', 'exchange'),
        (r'\btrocas\b', 'exchanges'),
        (r'\bsubstituição\b', 'substitution'),
        (r'\bsubstituições\b', 'substitutions'),
        (r'\breplacement\b', 'replacement'),
        (r'\breplacements\b', 'replacements'),
        (r'\balternância\b', 'alternation'),
        (r'\balternâncias\b', 'alternations'),
        (r'\brevezamento\b', 'alternation'),
        (r'\brevezamentos\b', 'alternations'),
        (r'\brotação\b', 'rotation'),
        (r'\brotações\b', 'rotations'),
        (r'\bgiro\b', 'rotation'),
        (r'\bgiros\b', 'rotations'),
        (r'\brevolução\b', 'revolution'),
        (r'\brevoluções\b', 'revolutions'),
        (r'\bciclo\b', 'cycle'),
        (r'\bciclos\b', 'cycles'),
        (r'\brepetição\b', 'repetition'),
        (r'\brepetições\b', 'repetitions'),
        (r'\biteração\b', 'iteration'),
        (r'\biterações\b', 'iterations'),
        (r'\blooping\b', 'looping'),
        (r'\bloopings\b', 'loopings'),
        (r'\bloop\b', 'loop'),
        (r'\bloops\b', 'loops'),
        (r'\blaço\b', 'loop'),
        (r'\blaços\b', 'loops'),
        (r'\bvolta\b', 'loop'),
        (r'\bvoltas\b', 'loops'),
        (r'\brecursão\b', 'recursion'),
        (r'\brecursões\b', 'recursions'),
        (r'\brecorrência\b', 'recurrence'),
        (r'\brecorrências\b', 'recurrences'),
        (r'\breaparição\b', 'reappearance'),
        (r'\breaparições\b', 'reappearances'),
        (r'\bretorno\b', 'return'),
        (r'\bretornos\b', 'returns'),
        (r'\bvolta\b', 'return'),
        (r'\bvoltas\b', 'returns'),
        (r'\bregresso\b', 'return'),
        (r'\bregressos\b', 'returns'),
        (r'\brestabelecimento\b', 'restoration'),
        (r'\brestabelecimentos\b', 'restorations'),
        (r'\brecuperação\b', 'recovery'),
        (r'\brecuperações\b', 'recoveries'),
        (r'\bresgate\b', 'recovery'),
        (r'\bresgates\b', 'recoveries'),
        (r'\brestauração\b', 'restoration'),
        (r'\brestaurações\b', 'restorations'),
        (r'\breconstituição\b', 'reconstitution'),
        (r'\breconstituições\b', 'reconstitutions'),
        (r'\breconstrução\b', 'reconstruction'),
        (r'\breconstruções\b', 'reconstructions'),
        (r'\breedificação\b', 'rebuilding'),
        (r'\breedificações\b', 'rebuildings'),
        (r'\brefazimento\b', 'redoing'),
        (r'\brefazimentos\b', 'redoings'),
        (r'\brenovação\b', 'renovation'),
        (r'\brenovações\b', 'renovations'),
        (r'\bmodernização\b', 'modernization'),
        (r'\bmodernizações\b', 'modernizations'),
        (r'\batualização\b', 'update'),
        (r'\batualizações\b', 'updates'),
        (r'\bupgrade\b', 'upgrade'),
        (r'\bupgrades\b', 'upgrades'),
        (r'\bmelhoramento\b', 'improvement'),
        (r'\bmelhoramentos\b', 'improvements'),
        (r'\baperfeiçoamento\b', 'enhancement'),
        (r'\baperfeiçoamentos\b', 'enhancements'),
        (r'\botimização\b', 'optimization'),
        (r'\botimizações\b', 'optimizations'),
        
        # Common phrases
        (r'\bpor exemplo\b', 'for example'),
        (r'\bpor favor\b', 'please'),
        (r'\bpor isso\b', 'therefore'),
        (r'\bpor fim\b', 'finally'),
        (r'\bpor último\b', 'lastly'),
        (r'\bprimeiro\b', 'first'),
        (r'\bsegundo\b', 'second'),
        (r'\bterceiro\b', 'third'),
        (r'\bquarto\b', 'fourth'),
        (r'\bquinto\b', 'fifth'),
        (r'\bsexto\b', 'sixth'),
        (r'\bsétimo\b', 'seventh'),
        (r'\boitavo\b', 'eighth'),
        (r'\bnono\b', 'ninth'),
        (r'\bdécimo\b', 'tenth'),
        (r'\banterior\b', 'previous'),
        (r'\banteriores\b', 'previous'),
        (r'\bpróximo\b', 'next'),
        (r'\bpróximos\b', 'next'),
        (r'\bpróxima\b', 'next'),
        (r'\bpróximas\b', 'next'),
        (r'\batual\b', 'current'),
        (r'\batuais\b', 'current'),
        (r'\bpresente\b', 'present'),
        (r'\bpresentes\b', 'present'),
        (r'\bpassado\b', 'past'),
        (r'\bpassados\b', 'past'),
        (r'\bpassada\b', 'past'),
        (r'\bpassadas\b', 'past'),
        (r'\bfuturo\b', 'future'),
        (r'\bfuturos\b', 'future'),
        (r'\bfutura\b', 'future'),
        (r'\bfuturas\b', 'future'),
        (r'\bnovo\b', 'new'),
        (r'\bnovos\b', 'new'),
        (r'\bnova\b', 'new'),
        (r'\bnovas\b', 'new'),
        (r'\bantigo\b', 'old'),
        (r'\bantigos\b', 'old'),
        (r'\bantiga\b', 'old'),
        (r'\bantigas\b', 'old'),
        (r'\bvelho\b', 'old'),
        (r'\bvelhos\b', 'old'),
        (r'\bvelha\b', 'old'),
        (r'\bvelhas\b', 'old'),
        (r'\bjovem\b', 'young'),
        (r'\bjovens\b', 'young'),
        (r'\brecente\b', 'recent'),
        (r'\brecentes\b', 'recent'),
        (r'\bremoto\b', 'remote'),
        (r'\bremotos\b', 'remote'),
        (r'\bremota\b', 'remote'),
        (r'\bremotas\b', 'remote'),
        (r'\bdistante\b', 'distant'),
        (r'\bdistantes\b', 'distant'),
        (r'\bpróximo\b', 'close'),
        (r'\bpróximos\b', 'close'),
        (r'\bpróxima\b', 'close'),
        (r'\bpróximas\b', 'close'),
        (r'\bperto\b', 'near'),
        (r'\blonge\b', 'far'),
        (r'\bdentro\b', 'inside'),
        (r'\bfora\b', 'outside'),
        (r'\bacima\b', 'above'),
        (r'\babaixo\b', 'below'),
        (r'\besquerda\b', 'left'),
        (r'\bdireita\b', 'right'),
        (r'\bfrente\b', 'front'),
        (r'\btrás\b', 'back'),
        (r'\bcentro\b', 'center'),
        (r'\bcentros\b', 'centers'),
        (r'\bmeio\b', 'middle'),
        (r'\bmeios\b', 'middles'),
        (r'\blado\b', 'side'),
        (r'\blados\b', 'sides'),
        (r'\bbordar\b', 'edge'),
        (r'\bbordas\b', 'edges'),
        (r'\bextremidade\b', 'extremity'),
        (r'\bextremidades\b', 'extremities'),
        (r'\bponta\b', 'tip'),
        (r'\bpontas\b', 'tips'),
        (r'\bfim\b', 'end'),
        (r'\bfins\b', 'ends'),
        (r'\bcomeço\b', 'beginning'),
        (r'\bcomeços\b', 'beginnings'),
        (r'\binício\b', 'start'),
        (r'\binícios\b', 'starts'),
        (r'\bprincipio\b', 'beginning'),
        (r'\bprincipios\b', 'beginnings'),
        (r'\borigem\b', 'origin'),
        (r'\borigens\b', 'origins'),
        (r'\braiz\b', 'root'),
        (r'\braízes\b', 'roots'),
        (r'\bbase\b', 'base'),
        (r'\bbases\b', 'bases'),
        (r'\bfundamento\b', 'foundation'),
        (r'\bfundamentos\b', 'foundations'),
        (r'\bestabelecimento\b', 'establishment'),
        (r'\bestabelecimentos\b', 'establishments'),
        (r'\binstituição\b', 'institution'),
        (r'\binstituições\b', 'institutions'),
        (r'\borganização\b', 'organization'),
        (r'\borganizações\b', 'organizations'),
        (r'\bessência\b', 'essence'),
        (r'\bessências\b', 'essences'),
        (r'\bnatureza\b', 'nature'),
        (r'\bnaturezas\b', 'natures'),
        (r'\bcaráter\b', 'character'),
        (r'\bcaráteres\b', 'characters'),
        (r'\bcaracterística\b', 'characteristic'),
        (r'\bcaracterísticas\b', 'characteristics'),
        (r'\btração\b', 'trait'),
        (r'\btraços\b', 'traits'),
        (r'\btraço\b', 'trait'),
        (r'\btraçair\b', 'trait'),
        (r'\btraçares\b', 'traits'),
        (r'\bdetalhe\b', 'detail'),
        (r'\bdetalhes\b', 'details'),
        (r'\bparticular\b', 'particular'),
        (r'\bparticulares\b', 'particulars'),
        (r'\bespecificidade\b', 'specificity'),
        (r'\bespecificidades\b', 'specificities'),
        (r'\bsingularidade\b', 'singularity'),
        (r'\bsingularidades\b', 'singularities'),
        (r'\bunicidade\b', 'uniqueness'),
        (r'\bunicidades\b', 'uniquenesses'),
        (r'\bexclusividade\b', 'exclusivity'),
        (r'\bexclusividades\b', 'exclusivities'),
        (r'\bpecularidade\b', 'peculiarity'),
        (r'\bpecularidades\b', 'peculiarities'),
        (r'\bidiossincrasia\b', 'idiosyncrasy'),
        (r'\bidiossincrasias\b', 'idiosyncrasies'),
        (r'\bmaneirismo\b', 'mannerism'),
        (r'\bmaneirismos\b', 'mannerisms'),
        (r'\bestilo\b', 'style'),
        (r'\bestilos\b', 'styles'),
        (r'\bmoda\b', 'fashion'),
        (r'\bmodas\b', 'fashions'),
        (r'\btendência\b', 'trend'),
        (r'\btendências\b', 'trends'),
        (r'\bcorrente\b', 'current'),
        (r'\bcorrentes\b', 'currents'),
        (r'\bfluxo\b', 'flow'),
        (r'\bfluxos\b', 'flows'),
        (r'\bcurso\b', 'course'),
        (r'\bcursos\b', 'courses'),
        (r'\bsequência\b', 'sequence'),
        (r'\bsequências\b', 'sequences'),
        (r'\borderm\b', 'order'),
        (r'\bordems\b', 'orders'),
        (r'\barrangement\b', 'arrangement'),
        (r'\barrangements\b', 'arrangements'),
        (r'\borganização\b', 'organization'),
        (r'\borganizações\b', 'organizations'),
        (r'\bestruturação\b', 'structuring'),
        (r'\bestruturações\b', 'structurings'),
        (r'\bdisposição\b', 'disposition'),
        (r'\bdisposições\b', 'dispositions'),
        (r'\bconfiguração\b', 'configuration'),
        (r'\bconfigurações\b', 'configurations'),
        (r'\bformatação\b', 'formatting'),
        (r'\bformatações\b', 'formattings'),
        (r'\blayout\b', 'layout'),
        (r'\blayouts\b', 'layouts'),
        (r'\bdesenho\b', 'drawing'),
        (r'\bdesenhos\b', 'drawings'),
        (r'\bdesign\b', 'design'),
        (r'\bdesigns\b', 'designs'),
        (r'\bprojeto\b', 'project'),
        (r'\bprojetos\b', 'projects'),
        (r'\bplano\b', 'plan'),
        (r'\bplanos\b', 'plans'),
        (r'\bplanejamento\b', 'planning'),
        (r'\bplanejamentos\b', 'plannings'),
        (r'\bprogramação\b', 'programming'),
        (r'\bprogramações\b', 'programmings'),
        (r'\bagenda\b', 'agenda'),
        (r'\bagendas\b', 'agendas'),
        (r'\bcronograma\b', 'schedule'),
        (r'\bcronogramas\b', 'schedules'),
        (r'\bhorário\b', 'schedule'),
        (r'\bhorários\b', 'schedules'),
        (r'\bcalendário\b', 'calendar'),
        (r'\bcalendários\b', 'calendars'),
        (r'\bdata\b', 'date'),
        (r'\bdatas\b', 'dates'),
        (r'\bdia\b', 'day'),
        (r'\bdias\b', 'days'),
        (r'\bhora\b', 'hour'),
        (r'\bhoras\b', 'hours'),
        (r'\bminuto\b', 'minute'),
        (r'\bminutos\b', 'minutes'),
        (r'\bsegundo\b', 'second'),
        (r'\bsegundos\b', 'seconds'),
        (r'\bmilissegundo\b', 'millisecond'),
        (r'\bmilissegundos\b', 'milliseconds'),
        (r'\bmicrossegundo\b', 'microsecond'),
        (r'\bmicrossegundos\b', 'microseconds'),
        (r'\bnanossegundo\b', 'nanosecond'),
        (r'\bnanossegundos\b', 'nanoseconds'),
        (r'\bunidade\b', 'unit'),
        (r'\bunidades\b', 'units'),
        (r'\bmedida\b', 'measure'),
        (r'\bmedidas\b', 'measures'),
        (r'\bmensuração\b', 'measurement'),
        (r'\bmensurações\b', 'measurements'),
        (r'\bquantificação\b', 'quantification'),
        (r'\bquantificações\b', 'quantifications'),
        (r'\bavaliação\b', 'evaluation'),
        (r'\bavaliações\b', 'evaluations'),
        (r'\bestimativa\b', 'estimate'),
        (r'\bestimativas\b', 'estimates'),
        (r'\baproximação\b', 'approximation'),
        (r'\baproximações\b', 'approximations'),
        (r'\bcálculo\b', 'calculation'),
        (r'\bcálculos\b', 'calculations'),
        (r'\bcomputação\b', 'computation'),
        (r'\bcomputações\b', 'computations'),
        (r'\bdeterminação\b', 'determination'),
        (r'\bdeterminações\b', 'determinations'),
        (r'\bobtenção\b', 'obtaining'),
        (r'\bobtenções\b', 'obtainings'),
        (r'\baquiseção\b', 'acquisition'),
        (r'\baquiseções\b', 'acquisitions'),
        (r'\baquisição\b', 'acquisition'),
        (r'\baquisições\b', 'acquisitions'),
        (r'\bcoleta\b', 'collection'),
        (r'\bcoletas\b', 'collections'),
        (r'\brecolha\b', 'collection'),
        (r'\brecolhas\b', 'collections'),
        (r'\bgathering\b', 'gathering'),
        (r'\bgatherings\b', 'gatherings'),
        (r'\bcoleção\b', 'collection'),
        (r'\bcoleções\b', 'collections'),
        (r'\baglomeração\b', 'agglomeration'),
        (r'\baglomerações\b', 'agglomerations'),
        (r'\bacumulação\b', 'accumulation'),
        (r'\bacumulações\b', 'accumulations'),
        (r'\barmaz enamento\b', 'storage'),
        (r'\barmazenamentos\b', 'storages'),
        (r'\bguarda\b', 'storage'),
        (r'\bguardas\b', 'storages'),
        (r'\bconservação\b', 'conservation'),
        (r'\bconservações\b', 'conservations'),
        (r'\bpreservação\b', 'preservation'),
        (r'\bpreservações\b', 'preservations'),
        (r'\bmanutenção\b', 'maintenance'),
        (r'\bmanutenções\b', 'maintenances'),
        (r'\bcuidado\b', 'care'),
        (r'\bcuidados\b', 'cares'),
        (r'\batenção\b', 'attention'),
        (r'\batenções\b', 'attentions'),
        (r'\bvigilância\b', 'vigilance'),
        (r'\bvigilâncias\b', 'vigilances'),
        (r'\bobservação\b', 'observation'),
        (r'\bobservações\b', 'observations'),
        (r'\bmonitoramento\b', 'monitoring'),
        (r'\bmonitoramentos\b', 'monitorings'),
        (r'\bacompanhamento\b', 'monitoring'),
        (r'\bacompanhamentos\b', 'monitorings'),
        (r'\bsupervisão\b', 'supervision'),
        (r'\bsupervisões\b', 'supervisions'),
        (r'\bfiscalização\b', 'inspection'),
        (r'\bfiscalizações\b', 'inspections'),
        (r'\binspeção\b', 'inspection'),
        (r'\binspeções\b', 'inspections'),
        (r'\bcontrole\b', 'control'),
        (r'\bcontroles\b', 'controls'),
        (r'\bregulação\b', 'regulation'),
        (r'\bregulações\b', 'regulations'),
        (r'\bregulamento\b', 'regulation'),
        (r'\bregulamentos\b', 'regulations'),
        (r'\bnorma\b', 'norm'),
        (r'\bnormas\b', 'norms'),
        (r'\bregra\b', 'rule'),
        (r'\bregras\b', 'rules'),
        (r'\bdiretriz\b', 'guideline'),
        (r'\bdiretrizes\b', 'guidelines'),
        (r'\blineamento\b', 'guideline'),
        (r'\blineamentos\b', 'guidelines'),
        (r'\borientação\b', 'orientation'),
        (r'\borientações\b', 'orientations'),
        (r'\bguia\b', 'guide'),
        (r'\bguias\b', 'guides'),
        (r'\bmanual\b', 'manual'),
        (r'\bmanuais\b', 'manuals'),
        (r'\binstrução\b', 'instruction'),
        (r'\binstruções\b', 'instructions'),
        (r'\bdirecão\b', 'direction'),
        (r'\bdireções\b', 'directions'),
        (r'\bindicação\b', 'indication'),
        (r'\bindicações\b', 'indications'),
        (r'\bsugestão\b', 'suggestion'),
        (r'\bsugestões\b', 'suggestions'),
        (r'\brecomendação\b', 'recommendation'),
        (r'\brecomendações\b', 'recommendations'),
        (r'\baconselhamento\b', 'advice'),
        (r'\baconselhamentos\b', 'advice'),
        (r'\bconselho\b', 'advice'),
        (r'\bconselhos\b', 'advice'),
        (r'\bdica\b', 'tip'),
        (r'\bdicas\b', 'tips'),
        (r'\bsugestão\b', 'hint'),
        (r'\bsugestões\b', 'hints'),
        (r'\bindication\b', 'hint'),
        (r'\bindications\b', 'hints'),
        (r'\bpista\b', 'clue'),
        (r'\bpistas\b', 'clues'),
        (r'\bvestígio\b', 'trace'),
        (r'\bvestígios\b', 'traces'),
        (r'\brasto\b', 'track'),
        (r'\brastos\b', 'tracks'),
        (r'\btrilha\b', 'trail'),
        (r'\btrilhas\b', 'trails'),
        (r'\bcaminho\b', 'path'),
        (r'\bcaminhos\b', 'paths'),
        (r'\brota\b', 'route'),
        (r'\brotas\b', 'routes'),
        (r'\bitinerário\b', 'itinerary'),
        (r'\bitinerários\b', 'itineraries'),
        (r'\btrajetória\b', 'trajectory'),
        (r'\btrajetórias\b', 'trajectories'),
        (r'\bpercurso\b', 'course'),
        (r'\bpercursos\b', 'courses'),
        (r'\bjornada\b', 'journey'),
        (r'\bjornadas\b', 'journeys'),
        (r'\bviagem\b', 'trip'),
        (r'\bviagens\b', 'trips'),
        (r'\bexpedição\b', 'expedition'),
        (r'\bexpedições\b', 'expeditions'),
        (r'\bexcursão\b', 'excursion'),
        (r'\bexcursões\b', 'excursions'),
        (r'\bpasseio\b', 'tour'),
        (r'\bpasseios\b', 'tours'),
        (r'\btour\b', 'tour'),
        (r'\btours\b', 'tours'),
        (r'\bvisita\b', 'visit'),
        (r'\bvisitas\b', 'visits'),
        (r'\bestadia\b', 'stay'),
        (r'\bestadias\b', 'stays'),
        (r'\bpermanência\b', 'stay'),
        (r'\bpermanências\b', 'stays'),
        (r'\bestancia\b', 'stay'),
        (r'\bestancias\b', 'stays'),
        (r'\bestudar\b', 'study'),
        (r'\bestudo\b', 'study'),
        (r'\bestudos\b', 'studies'),
        (r'\bpesquisa\b', 'research'),
        (r'\bpesquisas\b', 'research'),
        (r'\binvestigação\b', 'investigation'),
        (r'\binvestigações\b', 'investigations'),
        (r'\bexploração\b', 'exploration'),
        (r'\bexplorações\b', 'explorations'),
        (r'\bsondagem\b', 'probe'),
        (r'\bsondagens\b', 'probes'),
        (r'\bexame\b', 'exam'),
        (r'\bexames\b', 'exams'),
        (r'\bteste\b', 'test'),
        (r'\btestes\b', 'tests'),
        (r'\bprova\b', 'test'),
        (r'\bprovas\b', 'tests'),
        (r'\bavaliação\b', 'assessment'),
        (r'\bavaliações\b', 'assessments'),
        (r'\baferição\b', 'measurement'),
        (r'\baferições\b', 'measurements'),
        (r'\binstrução\b', 'instruction'),
        (r'\binstruções\b', 'instructions'),
        (r'\bnota\b', 'grade'),
        (r'\bnotas\b', 'grades'),
        (r'\bpontuação\b', 'score'),
        (r'\bpontuações\b', 'scores'),
        (r'\bqualificação\b', 'rating'),
        (r'\bqualificações\b', 'ratings'),
        (r'\bclassificação\b', 'classification'),
        (r'\bclassificações\b', 'classifications'),
        (r'\branking\b', 'ranking'),
        (r'\brankings\b', 'rankings'),
        (r'\bposicionamento\b', 'positioning'),
        (r'\bposicionamentos\b', 'positionings'),
        (r'\bordaming\b', 'ordering'),
        (r'\bordamings\b', 'orderings'),
        (r'\bsequenciamento\b', 'sequencing'),
        (r'\bsequenciamentos\b', 'sequencings'),
        (r'\bsériação\b', 'seriation'),
        (r'\bsériações\b', 'seriations'),
        (r'\bprogresão\b', 'progression'),
        (r'\bprogresões\b', 'progressions'),
        (r'\bseguimento\b', 'following'),
        (r'\bseguimentos\b', 'followings'),
        (r'\bsequela\b', 'sequel'),
        (r'\bsequelas\b', 'sequels'),
        (r'\bcontinuação\b', 'continuation'),
        (r'\bcontinuações\b', 'continuations'),
        (r'\bprosseguimento\b', 'continuation'),
        (r'\bprosseguimentos\b', 'continuations'),
        (r'\bprolongamento\b', 'extension'),
        (r'\bprolongamentos\b', 'extensions'),
        (r'\bextensão\b', 'extension'),
        (r'\bextensões\b', 'extensions'),
        (r'\bampliação\b', 'enlargement'),
        (r'\bampliações\b', 'enlargements'),
        (r'\bexpansão\b', 'expansion'),
        (r'\bexpansões\b', 'expansions'),
        (r'\bcrescimento\b', 'growth'),
        (r'\bcrescimentos\b', 'growths'),
        (r'\bdesenvolvimento\b', 'development'),
        (r'\bdesenvolvimentos\b', 'developments'),
        (r'\bevolução\b', 'evolution'),
        (r'\bevoluções\b', 'evolutions'),
        (r'\bprogresso\b', 'progress'),
        (r'\bprogressos\b', 'progresses'),
        (r'\bavanço\b', 'advance'),
        (r'\bavanços\b', 'advances'),
        (r'\bmelhoria\b', 'improvement'),
        (r'\bmelhorias\b', 'improvements'),
        (r'\baprimoramento\b', 'enhancement'),
        (r'\baprimoramentos\b', 'enhancements'),
        (r'\brefinamento\b', 'refinement'),
        (r'\brefinamentos\b', 'refinements'),
        (r'\bpolimento\b', 'polishing'),
        (r'\bpolimentos\b', 'polishings'),
        (r'\bacabamento\b', 'finishing'),
        (r'\bacabamentos\b', 'finishings'),
        (r'\bfinalização\b', 'finalization'),
        (r'\bfinalizações\b', 'finalizations'),
        (r'\bconclusão\b', 'conclusion'),
        (r'\bconclusões\b', 'conclusions'),
        (r'\bterminação\b', 'termination'),
        (r'\bterminações\b', 'terminations'),
        (r'\bencerramento\b', 'closure'),
        (r'\bencerramentos\b', 'closures'),
        (r'\bfechamento\b', 'closing'),
        (r'\bfechamentos\b', 'closings'),
        (r'\binterrupção\b', 'interruption'),
        (r'\binterrupções\b', 'interruptions'),
        (r'\bparada\b', 'stop'),
        (r'\bparadas\b', 'stops'),
        (r'\bcesseção\b', 'cessation'),
        (r'\bcesseções\b', 'cessations'),
        (r'\bcessação\b', 'cessation'),
        (r'\bcessações\b', 'cessations'),
        (r'\bsuspensão\b', 'suspension'),
        (r'\bsuspensões\b', 'suspensions'),
        (r'\binterrupação\b', 'break'),
        (r'\binterrupações\b', 'breaks'),
        (r'\bpausa\b', 'pause'),
        (r'\bpausas\b', 'pauses'),
        (r'\bintervalo\b', 'break'),
        (r'\bintervalos\b', 'breaks'),
        (r'\bdescanso\b', 'rest'),
        (r'\bdescansos\b', 'rests'),
        (r'\brepouso\b', 'rest'),
        (r'\brepousos\b', 'rests'),
        (r'\brelaxamento\b', 'relaxation'),
        (r'\brelaxamentos\b', 'relaxations'),
        (r'\bdistensão\b', 'relaxation'),
        (r'\bdistensões\b', 'relaxations'),
        (r'\balivio\b', 'relief'),
        (r'\balivios\b', 'reliefs'),
        (r'\bconforto\b', 'comfort'),
        (r'\bconfortos\b', 'comforts'),
        (r'\bcomodidade\b', 'comfort'),
        (r'\bcomodidades\b', 'comforts'),
        (r'\bconveniência\b', 'convenience'),
        (r'\bconveniências\b', 'conveniences'),
        (r'\bfacilidade\b', 'ease'),
        (r'\bfacilidades\b', 'ease'),
        (r'\bsimplicidade\b', 'simplicity'),
        (r'\bsimplicidades\b', 'simplicities'),
        (r'\bsingeleza\b', 'simplicity'),
        (r'\bsingelezas\b', 'simplicities'),
        (r'\bdescomplicação\b', 'simplicity'),
        (r'\bdescomplicações\b', 'simplicities'),
        (r'\binformalidade\b', 'informality'),
        (r'\binformalidades\b', 'informalities'),
        (r'\bdescontração\b', 'relaxation'),
        (r'\bdescontrações\b', 'relaxations'),
        (r'\binformalidade\b', 'casualness'),
        (r'\binformalidades\b', 'casualnesses'),
        (r'\bsoltura\b', 'looseness'),
        (r'\bsolturas\b', 'loosenesses'),
        (r'\bliberdade\b', 'freedom'),
        (r'\bliberdades\b', 'freedoms'),
        (r'\bautonomy\b', 'autonomy'),
        (r'\bautonomys\b', 'autonomies'),
        (r'\bautonomia\b', 'autonomy'),
        (r'\bautonomias\b', 'autonomies'),
        (r'\bindependência\b', 'independence'),
        (r'\bindependências\b', 'independences'),
        (r'\bemancipação\b', 'emancipation'),
        (r'\bemancipações\b', 'emancipations'),
        (r'\blibertação\b', 'liberation'),
        (r'\blibertações\b', 'liberations'),
        (r'\bsoltura\b', 'release'),
        (r'\bsolturas\b', 'releases'),
        (r'\bliberação\b', 'release'),
        (r'\bliberações\b', 'releases'),
        (r'\bdesoneração\b', 'exoneration'),
        (r'\bdesonerações\b', 'exonerations'),
        (r'\bisenção\b', 'exemption'),
        (r'\bisenções\b', 'exemptions'),
        (r'\bdispensa\b', 'exemption'),
        (r'\bdispensas\b', 'exemptions'),
        (r'\bexclusão\b', 'exclusion'),
        (r'\bexclusões\b', 'exclusions'),
        (r'\bomissão\b', 'omission'),
        (r'\bomissões\b', 'omissions'),
        (r'\bsupressão\b', 'suppression'),
        (r'\bsupressões\b', 'suppressions'),
        (r'\beliminação\b', 'elimination'),
        (r'\beliminações\b', 'eliminations'),
        (r'\bremoção\b', 'removal'),
        (r'\bremoções\b', 'removals'),
        (r'\bretiro\b', 'withdrawal'),
        (r'\bretiros\b', 'withdrawals'),
        (r'\bretirada\b', 'withdrawal'),
        (r'\bretiradas\b', 'withdrawals'),
        (r'\bextração\b', 'extraction'),
        (r'\bextrações\b', 'extractions'),
        (r'\babstração\b', 'abstraction'),
        (r'\babstrações\b', 'abstractions'),
        (r'\bseparação\b', 'separation'),
        (r'\bseparações\b', 'separations'),
        (r'\bisolamento\b', 'isolation'),
        (r'\bisolamentos\b', 'isolations'),
        (r'\bsegregação\b', 'segregation'),
        (r'\bsegregações\b', 'segregations'),
        (r'\bdiviño\b', 'division'),
        (r'\bdiviños\b', 'divisions'),
        (r'\bpartição\b', 'partition'),
        (r'\bpartições\b', 'partitions'),
        (r'\bfracionamento\b', 'fractionation'),
        (r'\bfracionamentos\b', 'fractionations'),
        (r'\bquebra\b', 'break'),
        (r'\bquebras\b', 'breaks'),
        (r'\bruptura\b', 'rupture'),
        (r'\brupturas\b', 'ruptures'),
        (r'\bfratura\b', 'fracture'),
        (r'\bfraturas\b', 'fractures'),
        (r'\bfenda\b', 'crack'),
        (r'\bfendas\b', 'cracks'),
        (r'\bgreta\b', 'crack'),
        (r'\bgretas\b', 'cracks'),
        (r'\brabhaduraura\b', 'crack'),
        (r'\brabhadurauras\b', 'cracks'),
        (r'\bdano\b', 'damage'),
        (r'\bdanos\b', 'damages'),
        (r'\bprejuízo\b', 'damage'),
        (r'\bprejuízos\b', 'damages'),
        (r'\bavaria\b', 'damage'),
        (r'\bavarias\b', 'damages'),
        (r'\bdefeito\b', 'defect'),
        (r'\bdefeitos\b', 'defects'),
        (r'\bfalha\b', 'failure'),
        (r'\bfalhas\b', 'failures'),
        (r'\bfal\b', 'failure'),
        (r'\bfails\b', 'failures'),
        (r'\berro\b', 'error'),
        (r'\berros\b', 'errors'),
        (r'\bengano\b', 'mistake'),
        (r'\benganos\b', 'mistakes'),
        (r'\bequívoco\b', 'error'),
        (r'\bequívocos\b', 'errors'),
        (r'\blaps\b', 'lapse'),
        (r'\blapses\b', 'lapses'),
        (r'\bdescuido\b', 'oversight'),
        (r'\bdescuidos\b', 'oversights'),
        (r'\bomissão\b', 'omission'),
        (r'\bomissões\b', 'omissions'),
        (r'\besquecimento\b', 'forgetfulness'),
        (r'\besquecimentos\b', 'forgetfulness'),
        (r'\bamné sia\b', 'amnesia'),
        (r'\bamnésias\b', 'amnesias'),
        (r'\bperda de memória\b', 'memory loss'),
        (r'\bperdas de memória\b', 'memory losses'),
        (r'\bestendemos\b', 'we extend'),
        (r'\bestende\b', 'extends'),
        (r'\bespecificação\b', 'specification'),
        (r'\bespecificações\b', 'specifications'),
        
        # Common typos from bad translation
        (r'\bairray\b', 'array'),
        (r'\bgerairá\b', 'will generate'),
        (r'\bgerair\b', 'generate'),
        (r'\bvisualizair\b', 'visualize'),
        (r'\bcairregair\b', 'load'),
        (r'\bcarregair\b', 'load'),
        (r'\bexibair\b', 'display'),
        (r'\bexecutair\b', 'execute'),
        (r'\baplicair\b', 'apply'),
        (r'\bprocessair\b', 'process'),
        (r'\bmostrair\b', 'show'),
        (r'\bplotair\b', 'plot'),
        (r'\bcalculair\b', 'calculate'),
        (r'\bmairkers\b', 'markers'),
        (r'\bmairker\b', 'marker'),
        (r'\bshowsdos\b', 'shown'),
        (r'\bshowos\b', 'show'),
        (r'\busesmos\b', 'we use'),
        (r'\busemos\b', 'we use'),
        (r'\busair\b', 'use'),
        (r'\busará\b', 'will use'),
        (r'\bsamplemos\b', 'we sample'),
        (r'\bsampleair\b', 'sample'),
        (r'\bsampleda\b', 'sampled'),
        (r'\bsampledos\b', 'sampled'),
        (r'\bstartsr\b', 'starts'),
        (r'\bstartsmos\b', 'we start'),
        (r'\bimportsindo\b', 'importing'),
        (r'\bimportsndo\b', 'importing'),
        (r'\bclasss\b', 'class'),
        (r'\blasts\b', 'last'),
        (r'\bfirsts\b', 'first'),
        (r'\bin time of\b', 'instead of'),
        (r'\bin the time of\b', 'instead of'),
        (r'\bat vez of\b', 'instead of'),
        (r'\bat time of\b', 'instead of'),
        (r'\blines continuous\b', 'continuous lines'),
        (r'\bline continuous\b', 'continuous line'),
        (r'\bdiferente\b', 'different'),
        (r'\bdobro\b', 'double'),
        (r'\bcada\b', 'each'),
        (r'\bin which\b', 'in which'),
        (r'\bprecisair\b', 'need'),
        (r'\bneedá\b', 'need'),
        (r'\bin cair\b', 'in'),
        (r'\b a right\b', 'to the right'),
        (r'\ba left\b', 'to the left'),
        (r'\bsenoide\b', 'sinusoid'),
        (r'\bsenoides\b', 'sinusoids'),
        (r'\bapproximation\b', 'approximation'),
        (r'\brepresentação\b', 'representation'),
        (r'\brepresentações\b', 'representations'),
    ]
    
    # Apply replacements in order
    for pattern, replacement in replacements:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    
    return text

def clean_translate_code_comment(text):
    """Translate code comments from Portuguese to English."""
    # For now, use the same function
    return clean_translate_markdown(text)

def process_notebook(pt_file, en_file):
    """Process a single notebook file."""
    print(f"Processing: {os.path.basename(en_file)}")
    
    try:
        # Read Portuguese original
        with open(pt_file, 'r', encoding='utf-8') as f:
            pt_nb = json.load(f)
        
        # Read English version
        with open(en_file, 'r', encoding='utf-8') as f:
            en_nb = json.load(f)
        
        # Process all cells
        changes = 0
        for i, en_cell in enumerate(en_nb['cells']):
            if en_cell['cell_type'] == 'markdown':
                # Translate markdown
                original_source = ''.join(en_cell['source'])
                translated_source = clean_translate_markdown(original_source)
                
                if original_source != translated_source:
                    changes += 1
                    # Split back into lines preserving line breaks
                    lines = translated_source.split('\n')
                    en_cell['source'] = [line + '\n' if i < len(lines) - 1 else line 
                                        for i, line in enumerate(lines)]
            
            elif en_cell['cell_type'] == 'code':
                # Translate code comments (lines starting with #)
                original_source = ''.join(en_cell['source'])
                lines = original_source.split('\n')
                translated_lines = []
                
                for line in lines:
                    stripped = line.strip()
                    if stripped.startswith('#'):
                        # Translate comment
                        translated_line = clean_translate_code_comment(line)
                        translated_lines.append(translated_line)
                    else:
                        # Keep code as-is
                        translated_lines.append(line)
                
                translated_source = '\n'.join(translated_lines)
                
                if original_source != translated_source:
                    changes += 1
                    lines = translated_source.split('\n')
                    en_cell['source'] = [line + '\n' if i < len(lines) - 1 else line 
                                        for i, line in enumerate(lines)]
        
        # Write back
        if changes > 0:
            with open(en_file, 'w', encoding='utf-8') as f:
                json.dump(en_nb, f, ensure_ascii=False, indent=1)
            print(f"  ✓ Fixed {changes} cells")
        else:
            print(f"  ✓ No changes needed")
        
        return True
    except Exception as e:
        print(f"  ✗ Error: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    """Main function."""
    # Find all English notebook files
    base_dir = '/home/runner/work/BioSignalAndImgProcessing/BioSignalAndImgProcessing/assignments'
    en_files = sorted([f for f in os.listdir(base_dir) if f.endswith('_en.ipynb')])
    
    print(f"Found {len(en_files)} English notebook files to process\n")
    
    success = 0
    for en_filename in en_files:
        en_file = os.path.join(base_dir, en_filename)
        pt_file = en_file.replace('_en.ipynb', '.ipynb')
        
        if not os.path.exists(pt_file):
            print(f"⚠ Skipping {en_filename} - no Portuguese original found")
            continue
        
        if process_notebook(pt_file, en_file):
            success += 1
        print()
    
    print(f"\n{'='*60}")
    print(f"Completed: {success}/{len(en_files)} files processed successfully")
    print(f"{'='*60}")

if __name__ == '__main__':
    main()
